### ISSUE TITLE
jfsrec segfaults on large drives.

### ISSUE THREAD

**Issue by ghost** [jbar/jfsrec#1]
I am using the version from this repo and compiled with GCC 7.
I accidentally deleted a file from my backup drive and when I run `jfsrec` on it, after scanning it segfaults on "Searching for file parents and names".Run the program again and it segfaults on the same spot.
Console output:

    root[0,0,78]:/usr/home/pthfdr/jfsrec-master/src# ./jfsrec --output ./OUTPUT --logdir ./LOGS --device /dev/sdc --first SDDUMP.cpio --last SDDUMP.cpio --skip-unsane-extents
    starting...
    'first' regex: SDDUMP.cpio
    'last' regex: SDDUMP.cpio
    Opened device: /dev/sdc
    7.27Tb  Blocksize: 4096
    Skipping scan.
    Loading inodes... [Done] 148069 inodes in total.
    Loading invalidated inodes...Number of invalidated inodes: 123801
    Scan done...
    
    Total number of inodes stored:148069
    Number of
      Directories: 12289
      files: 129603
      symlinks: 6177
      special: 0
      unallocated: 0
    Total number of inodes stored:148069
    Number of
      Directories: 12289
      files: 129603
      symlinks: 6177
      special: 0
      unallocated: 0
    
    
    Searching for directory parents
    
    0%   10   20   30   40   50   60   70   80   90   100%
    |----|----|----|----|----|----|----|----|----|----|
    ***************************************************
    
    
    Searching for file parents and names
            3943955450368 - 10303/148100 -> 6.95679% The process was killed by SIGSEGV: Segmentation fault
The only lines added to `dmesg` is:
`jfsrec[2551]: segfault at 7ffc80cfc2b8 ip 0000557e7c1a4f33 sp 00007ffc80cfc2c0 error 6 in jfsrec[557e7c182000+46000],so clearly it is not a hardware issue.
I ran the included `jfsrec_rm_logged_inode` and tried again,but the result is the same.

**Comment by jbar** [comment]
cf. README.md :

Huu... segfault on a given inode

Sometime segfault may occurs on some given inode (like this https://pastebin.com/raw/cGhZKZHm) As jfsrec is not very active, and nobody has time to understand and fix this problem, there is a little bash script to help removed such inode from logfiles, so jfsrec will ignore them when re-invoqued with same options. Eg:

% jfsrec_rm_logged_inode --logdir /mnt/terabyteraid/logs 8192

------
If you have time for that challenge, u can try to fix. I don't and just wrote src/jfsrec_rm_logged_inode as a workaround.

**Comment by jbar** [comment]
I also changed cpp files to display inodes causing segfaults, but i didn't uncomment some of this trace. So u may have to uncomment some source lines and rebuild. cf:  
https://github.com/jbar/jfsrec/commit/857536b73d62cdcb576357097b9d6c2df23ae36f
